function orders = executeTWAP(sym, Q_total, barIdx, totalBars, side)
% side = 'BUY' or 'SELL'
    remainingBars = totalBars - barIdx + 1;
    clip = ceil(Q_total / remainingBars);
    orders = struct( ...
        'symbol', sym, ...
        'side',   side, ...
        'size',   clip, ...
        'type',   'MKT');  % Use 'LMT' with a price field for limit orders.
end
